#!/bin/bash
# start sxhkd
pgrep -x sxhkd >/dev/null || sxhkd &

# setting x11 and other values
$HOME/.config/bspwm/launch.sh
trash-empty 7
sleep 2s
xset dpms 0 0 0
xset s noblank
xset s noexpose
xset s off
xset -dpms
bluetoothctl discoverable off
bluetoothctl pairing off
bluetoothctl scan off
bluetoothctl power off

# pointer settings
bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr

# windows settings
bspc config pointer_motion_interval 1
bspc config border_width 2
bspc config window_gap 8
bspc config normal_border_color "#282828"
bspc config focused_border_color "#8ec07c"
bspc config presel_feedback_color "#8ec07c"
bspc config split_ratio 0.52
bspc config automatic_scheme longest_side
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules
bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a Rofi state=floating border=off

# Auto start programs:
feh --randomize --bg-fill $HOME/Images/Wallpapers &
killall succade
crontab $HOME/.config/bspwm/crontab-job
$HOME/.local/bin/succade &
xdo lower -a succade
killall dunst
dunst &
pkill -USR1 -x sxhkd
